### ISSUE TITLE
Open tournaments table is left aligned (forum missing)

### ISSUE THREAD

**Issue by millsaj** [prettierlichess/prettierlichess#116]
![image](https://user-images.githubusercontent.com/12159487/193882912-bd27ef85-ea9d-4caa-b24a-89246a5136ce.png)

The open tournaments table is shown with an empty space to the right. Looks like from the grid layout below that the forum is supposed to sit in the empty space.

```css
main.lobby {
	grid-template-areas:
		'app tv tv side'
		'table blog blog support'
		'leader puzzle puzzle winner'
		'tours tours forum forum'
		'. simuls simuls .'
		'. about about .' !important;
	grid-template-columns: minmax(400px, 1fr) 1fr 1fr minmax(400px, 1fr) !important;
	grid-template-rows: minmax(1fr, 800px) repeat(2, fit-content(0)) !important;
}
```

**Comment by millsaj** [comment]
Has lichess removed to forum from the home page entirely? (seems like it has to me)

Maybe we should change to this?
```css
main.lobby {
	grid-template-areas:
		'app tv tv side'
		'table blog blog support'
		'leader puzzle puzzle winner'
		'. tours tours .'
		'. simuls simuls .'
		'. about about .' !important;
	grid-template-columns: minmax(400px, 1fr) 1fr 1fr minmax(400px, 1fr) !important;
	grid-template-rows: minmax(1fr, 800px) repeat(2, fit-content(0)) !important;
}
```
