### ISSUE TITLE
Extension is not available in Chrome Web Store

### ISSUE THREAD

**Issue by krenddelxxl** [prettierlichess/prettierlichess#241]
"This extension is no longer available because it doesn't follow best practices for Chrome extensions."
<-- On the extension page

![Image](https://github.com/user-attachments/assets/92ca352d-b0cc-414d-b912-9ba2ddfb2528)

**Comment by acschwartz** [comment]
Is this extension still being maintained?

**Comment by noahsemus** [comment]
Hiya folks -- sorry for the hiatus. The latest main should now have support for manifest v3. Thanks to whoever put out that PR. 

Regarding the store listing, I transferred ownership of the chrome store listing to @kieferro but unfortunately it seems he's been away for awhile (much like myself). I'm back with a vengeance, but I've reached out to him to see if he could transfer it back. 

If I don't hear from him, I'll need to make a new store listing. Hopefully it'll be back up soon.

**Comment by noahsemus** [comment]
Gonna make a new listing soon. Just want to close out outstanding FF & visual bugs.

**Comment by Siderite** [comment]
As help, here are the CSS fixes I've implemented in LiChess Tools for the existing Prettier version:
```css
body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties #dasher_app {
  overflow: visible !important;
}

body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties .analyse__side {
  border: none !important;
  backdrop-filter: none !important;
  background: none !important;
}

body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties .lobby__side > div {
  overflow: hidden;
  min-height: max-content;
}

@media (min-width: 800px) {
  body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties .gamebook {
    margin-left: -1em !important;
  }
}

body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties .analyse:not(.has-players) {
  margin-top: 0 !important;
}

body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties .analyse .gamebook .comment:has(button.lichessTools-readComments):not(.hinted, :has(button.hint)) {
  padding-bottom: 0;
}

html:has(body.lichessTools.lichessTools-prettier.lichessTools-theme_fixThirdParties.lichessTools-hasBoardBackground)[style*="#FFFFFF00"] main cg-board::before {
  background: var(--board-background) !important;
  background-size: 100% 100% !important;
}
```

Also, when you have published the Manifest V3 version, let us know, I'll test it.
